---
- name: Set up Ghost CMS with Docker
  hosts: ranchimall
  become: yes
  vars_files:
    - vars.yml
  tasks:
    # - name: Ensure Docker is installed
    #   apt:
    #     name: docker.io
    #     state: present
    #   become: yes

    # - name: Install Docker SDK for Python
    #   pip:
    #     name: docker
    #     state: present
    #   become: yes

    - name: Create a Docker network
      docker_network:
        name: "{{ ghost_network_name }}"
        state: present  # Ensure the network exists

    - name: Create Docker volume for Ghost CMS data
      docker_volume:
        name: "{{ ghost_volume_name }}"
        state: present  # Ensure the volume exists

    - name: Pull the Ghost image
      docker_image:
        name: "{{ ghost_image }}"
        source: pull  # Ensure the latest Ghost image is pulled

    - name: Remove existing Ghost CMS container if it exists
      docker_container:
        name: "{{ ghost_container_name }}"
        state: absent
        force_kill: yes

    - name: Run the Ghost CMS container
      docker_container:
        name: "{{ ghost_container_name }}"
        image: "{{ ghost_image }}"
        state: started
        restart_policy: always  # Ensure the container restarts on failure
        env: "{{ ghost_env }}"  # Set the environment variables for the container
        published_ports:
          - "{{ ghost_port_mapping }}"  # Map host port to container port
        volumes:
          - "{{ ghost_volume_name }}:/var/lib/ghost/content"  # Mount the volume for persistent data